local builtin = require("telescope.builtin")
local v = require("johnsmoit.visual")
vim.keymap.set("n", "<leader>ff", builtin.find_files, {})
vim.keymap.set("n", "<C-p>", builtin.git_files, {})
vim.keymap.set("n", "<leader>fs", function()
	builtin.grep_string({ search = vim.fn.input("Grep > ") })
end)

vim.keymap.set("v", "<leader>fv", function()
    local text = v.selected_text()
    print(text)
    print("HELOOOOOOOOOOOOOOOOOOOOO")
    builtin.grep_string({search = text})
end)
